# Generated by Django 3.2.23 on 2024-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddLeaseProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000)),
                ('premises_address', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('monthly_rent', models.CharField(max_length=500)),
                ('lessee_name', models.CharField(max_length=1000)),
                ('lessor_name', models.CharField(max_length=1000)),
                ('lessee_add', models.CharField(max_length=1000)),
                ('lessor_add', models.CharField(max_length=1000)),
                ('lessee_contact', models.CharField(max_length=11)),
                ('lessor_contact', models.CharField(max_length=11)),
                ('brokerage_day_lessee', models.CharField(max_length=500)),
                ('brokerage_day_lessor', models.CharField(max_length=500)),
                ('brokerage_lessee', models.CharField(max_length=500)),
                ('amount_lessee', models.CharField(max_length=1000)),
                ('pending_lessee', models.IntegerField()),
                ('brokerage_lessor', models.CharField(max_length=500)),
                ('amount_lessor', models.CharField(max_length=1000)),
                ('pending_lessor', models.IntegerField()),
                ('mop_lessee', models.IntegerField()),
                ('mop_lessor', models.IntegerField()),
                ('cash', models.CharField(max_length=1000)),
                ('cash_lessor', models.CharField(max_length=1000)),
                ('brokerage_due', models.CharField(max_length=1000)),
                ('total_amt', models.CharField(max_length=1000)),
                ('pending_amt', models.CharField(max_length=1000)),
                ('bank_name_lessee', models.CharField(max_length=1000)),
                ('date_lessee', models.DateField()),
                ('cheque_lessee', models.CharField(max_length=1000)),
                ('bank_name_lessor', models.CharField(max_length=1000)),
                ('date_lessor', models.DateField()),
                ('cheque_lessor', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'add_lease_property',
            },
        ),
    ]
