# Generated by Django 3.2.23 on 2024-01-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addleaseproperty',
            options={'managed': True},
        ),
    ]
