# Generated by Django 3.2.23 on 2024-01-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_agegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyBoughtProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'already_bought_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('created_by', models.IntegerField()),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('bank_id', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('created_by_user', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('modified_by', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'bank_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingStatusColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'booking_status_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('bsp', models.FloatField()),
                ('additional', models.FloatField()),
                ('total_brokerage', models.FloatField()),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by_user', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'brokerage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrokeragePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('mode_payment_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=200)),
                ('payment_date', models.DateField()),
                ('cheque_trans_date', models.IntegerField()),
                ('cheque_number_trans', models.CharField(max_length=200)),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'brokerage_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrokeragePaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('re_schedule', models.DateTimeField()),
                ('label', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=11)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'brokerage_payment_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('mode_payment_id', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('bank_name', models.CharField(max_length=500)),
                ('cheque_trans_date', models.IntegerField()),
                ('cheque_number_trans', models.CharField(max_length=200)),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'broker_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'builder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CallDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'call_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('state_id', models.IntegerField()),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('mode_payment_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=300)),
                ('cheque_trans_date', models.DateTimeField()),
                ('cheque_number_trans', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField()),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'commission_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('broker_id', models.IntegerField()),
                ('commission_amount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('builder_discount', models.IntegerField()),
                ('on_form', models.CharField(max_length=200)),
                ('interest_leived', models.IntegerField()),
                ('by_credit_note', models.CharField(max_length=200)),
                ('credit_commission', models.IntegerField()),
                ('net_cost_to_customer', models.IntegerField()),
                ('net_cost_to_builder', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_additional_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAdditionalDetailsBkp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('broker_id', models.IntegerField()),
                ('commission_amount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('on_form', models.CharField(max_length=200)),
                ('by_credit_note', models.CharField(max_length=200)),
                ('credit_commission', models.IntegerField()),
                ('net_cost_to_customer', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_additional_details-bkp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('mode_payment_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=300)),
                ('cheque_trans_date', models.DateTimeField()),
                ('payment_date', models.DateField()),
                ('cheque_number_trans', models.CharField(max_length=100)),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'customer_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=100)),
                ('father_husband_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('c_address', models.CharField(max_length=100)),
                ('city', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('pan_no', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('anniversary_date', models.DateTimeField()),
                ('co_applicant', models.CharField(max_length=250)),
                ('co_applicant_date', models.DateTimeField()),
                ('booking_date', models.DateTimeField()),
                ('plan_id', models.IntegerField()),
                ('plan_type_id', models.IntegerField()),
                ('plan_mode', models.IntegerField()),
                ('loan_interested', models.CharField(max_length=10)),
                ('loan_amount', models.IntegerField()),
                ('loan_status', models.CharField(max_length=10)),
                ('booking_amount_approved', models.IntegerField()),
                ('loan_approved', models.IntegerField()),
                ('other_approved', models.IntegerField()),
                ('booking_status', models.CharField(max_length=50)),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by_user', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'customer_management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('re_schedule', models.DateTimeField()),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_payment_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('builder_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('flat_no', models.CharField(max_length=250)),
                ('parking_charges', models.IntegerField()),
                ('plc', models.IntegerField()),
                ('bsp', models.IntegerField()),
                ('edc_idc', models.IntegerField()),
                ('ifms', models.IntegerField()),
                ('club_membership', models.IntegerField()),
                ('power_back_up', models.IntegerField()),
                ('any_other_charges', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_product_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dailycall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(blank=True, max_length=3, null=True)),
                ('calldatetime', models.DateTimeField(db_column='calldateTime')),
                ('regardingcalldetail', models.TextField(db_column='regardingCallDetail')),
                ('call_to_lead_id', models.IntegerField()),
                ('call_by_user', models.IntegerField()),
                ('schedule_id', models.IntegerField(blank=True, null=True)),
                ('project_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dailycall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('array2', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'delete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=300)),
                ('dependent_field', models.IntegerField()),
            ],
            options={
                'db_table': 'employment_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expensehead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'expensehead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.IntegerField()),
                ('expensetype', models.IntegerField(db_column='expenseType')),
                ('projectid', models.IntegerField(db_column='projectId')),
                ('expense_main_id', models.IntegerField()),
                ('expense_date', models.DateTimeField()),
                ('expense_name', models.CharField(max_length=200)),
                ('expense_detail', models.TextField()),
                ('amount', models.FloatField()),
                ('mode_payment_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=300)),
                ('cheque_trans_date', models.DateTimeField()),
                ('cheque_number_trans', models.CharField(max_length=100)),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by_user', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'expense_management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expensesubhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_main_id', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'expensesubhead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'family_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('imagename', models.CharField(db_column='imageName', max_length=350)),
            ],
            options={
                'db_table': 'gallery_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'lead_age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'lead_phase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_name', models.CharField(max_length=300)),
                ('source', models.IntegerField()),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('short_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('assign_user_id', models.IntegerField()),
                ('assigned_by_user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('assign_date_time', models.DateTimeField(blank=True, null=True)),
                ('accepted_status', models.CharField(max_length=1)),
                ('property_type', models.IntegerField()),
                ('response_time', models.IntegerField()),
                ('zone_type', models.IntegerField(blank=True, null=True)),
                ('project_type', models.IntegerField(blank=True, null=True)),
                ('project_type_multiple', models.CharField(max_length=500)),
                ('budget_type', models.IntegerField(blank=True, null=True)),
                ('inventory_type', models.IntegerField(blank=True, null=True)),
                ('product_type', models.IntegerField(blank=True, null=True)),
                ('created_by_user', models.IntegerField()),
                ('leaddelete', models.CharField(db_column='leadDelete', max_length=1)),
                ('modified_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('lessor', models.CharField(blank=True, max_length=200, null=True)),
                ('lessoramount', models.IntegerField(blank=True, db_column='lessorAmount', null=True)),
                ('lessordays', models.CharField(blank=True, db_column='lessorDays', max_length=300, null=True)),
                ('lessee', models.CharField(blank=True, max_length=300, null=True)),
                ('lesseeamonut', models.IntegerField(blank=True, db_column='lesseeAmonut', null=True)),
                ('lesseedays', models.CharField(blank=True, db_column='lesseeDays', max_length=100, null=True)),
                ('paydate', models.DateField(blank=True, db_column='payDate', null=True)),
                ('totalamount', models.IntegerField(blank=True, db_column='totalAmount', null=True)),
                ('pendingamount', models.IntegerField(blank=True, db_column='pendingAmount', null=True)),
                ('age_group', models.IntegerField(blank=True, null=True)),
                ('working_member', models.IntegerField()),
                ('already_bought_property', models.IntegerField()),
                ('nature_of_lead', models.IntegerField()),
                ('number_of_visits', models.IntegerField()),
                ('family_status', models.IntegerField()),
                ('residential_status', models.IntegerField()),
                ('residential_country', models.CharField(max_length=300)),
                ('employment_status', models.IntegerField()),
                ('profession', models.IntegerField()),
                ('profession_other', models.CharField(max_length=300)),
                ('nature_of_business', models.IntegerField()),
                ('nob_other', models.CharField(max_length=300)),
                ('lead_status', models.IntegerField()),
                ('tracker', models.IntegerField()),
                ('builder', models.IntegerField()),
                ('lead_age', models.IntegerField()),
            ],
            options={
                'db_table': 'leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lead_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManageBuilders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=255, unique=True)),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by_user', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'manage_builders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Managelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premises_address', models.TextField()),
                ('lessee', models.CharField(max_length=250)),
                ('lesor', models.CharField(max_length=250)),
                ('rent_per_month', models.IntegerField()),
                ('lease_start_date', models.DateTimeField()),
                ('security', models.IntegerField()),
                ('maintenace_charges', models.IntegerField()),
                ('increase_yearly', models.IntegerField()),
                ('service_tax', models.IntegerField()),
                ('property_tax', models.IntegerField()),
                ('agrement_time', models.CharField(max_length=500)),
                ('agreement_sign', models.CharField(max_length=500)),
                ('agreed_reg_charges', models.IntegerField()),
                ('advance_token', models.IntegerField()),
                ('owner_side_pending_work', models.CharField(max_length=500)),
                ('documents_required', models.TextField()),
                ('other_comments', models.TextField()),
                ('witness_1', models.CharField(max_length=500)),
                ('witness_2', models.CharField(max_length=500)),
                ('created_by_user', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('modified_by', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'managelease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManageProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('project_type_main_id', models.IntegerField()),
                ('builder_id', models.IntegerField()),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by_user', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'manage_projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManageProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('property_size', models.CharField(max_length=255)),
                ('property_rate', models.CharField(max_length=255)),
                ('property_type_sub_id', models.IntegerField()),
                ('propertytotal', models.FloatField(db_column='propertyTotal')),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by_user', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'manage_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagePropertySubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_property_type_id', models.IntegerField()),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'manage_property_sub_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagePropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'manage_property_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManageSubBrokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('city_id', models.IntegerField()),
                ('created_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by_user', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'manage_sub_brokers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'mode_of_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NatureOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('other_field', models.IntegerField()),
            ],
            options={
                'db_table': 'nature_of_business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NatureOfLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'nature_of_lead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NumberOfVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'number_of_visits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'payment_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'db_table': 'payment_plan_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'payment_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_permissions', models.TextField()),
            ],
            options={
                'db_table': 'permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'product_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('other_field', models.IntegerField()),
            ],
            options={
                'db_table': 'profession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone_id', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'project_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('size', models.CharField(blank=True, max_length=350, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=350, null=True)),
                ('dimension', models.CharField(blank=True, max_length=350, null=True)),
                ('furnished_type', models.CharField(blank=True, max_length=1, null=True)),
                ('negotiable_price', models.CharField(blank=True, max_length=1, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=350, null=True)),
                ('station', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('pic_gallery', models.CharField(blank=True, max_length=1, null=True)),
                ('brokerage', models.CharField(blank=True, db_column='Brokerage', max_length=2, null=True)),
                ('sq_ft_price', models.CharField(blank=True, max_length=350, null=True)),
                ('range', models.IntegerField()),
                ('floor_no', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=1)),
                ('sign_age', models.CharField(max_length=1)),
                ('month_rent', models.CharField(max_length=200)),
                ('inventory_available', models.CharField(max_length=1)),
                ('last_auth_date', models.DateField()),
                ('comment', models.CharField(max_length=1000)),
                ('created_by_user', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'property_lease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'property_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'range_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResidentialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country_field', models.IntegerField()),
            ],
            options={
                'db_table': 'residential_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'response_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('schedule_by_user', models.IntegerField()),
                ('nextdatetime', models.DateTimeField(blank=True, db_column='nextDateTime', null=True)),
                ('nexttype', models.CharField(db_column='nextType', max_length=1)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slabtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('val', models.FloatField()),
            ],
            options={
                'db_table': 'slabtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('zone_id', models.IntegerField()),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('dependent_field', models.IntegerField()),
            ],
            options={
                'db_table': 'tracker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('department_id', models.IntegerField()),
                ('users_type', models.IntegerField()),
                ('join_date', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usersession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
            ],
            options={
                'db_table': 'usersession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'usertype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'working_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('country_id', models.IntegerField()),
            ],
            options={
                'db_table': 'zone',
                'managed': False,
            },
        ),
    ]
