# Generated by Django 3.2.23 on 2024-01-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alreadyboughtproperty_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
