# Generated by Django 3.2.23 on 2024-01-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_leads_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={},
        ),
    ]
