# Generated by Django 3.2.23 on 2024-01-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_leads_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_name', models.CharField(blank=True, max_length=300, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('assign_user_id', models.IntegerField(blank=True, null=True)),
                ('assigned_by_user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('assign_date_time', models.DateTimeField(blank=True, null=True)),
                ('accepted_status', models.CharField(blank=True, max_length=1, null=True)),
                ('property_type', models.IntegerField(blank=True, null=True)),
                ('response_time', models.IntegerField(blank=True, null=True)),
                ('zone_type', models.IntegerField(blank=True, null=True)),
                ('project_type', models.IntegerField(blank=True, null=True)),
                ('project_type_multiple', models.CharField(blank=True, max_length=500, null=True)),
                ('budget_type', models.IntegerField(blank=True, null=True)),
                ('inventory_type', models.IntegerField(blank=True, null=True)),
                ('product_type', models.IntegerField(blank=True, null=True)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('leaddelete', models.CharField(blank=True, max_length=1, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('lessor', models.CharField(blank=True, max_length=200, null=True)),
                ('lessoramount', models.IntegerField(blank=True, null=True)),
                ('lessordays', models.CharField(blank=True, max_length=300, null=True)),
                ('lessee', models.CharField(blank=True, max_length=300, null=True)),
                ('lesseeamonut', models.IntegerField(blank=True, null=True)),
                ('lesseedays', models.CharField(blank=True, max_length=100, null=True)),
                ('totalamount', models.IntegerField(blank=True, null=True)),
                ('pendingamount', models.IntegerField(blank=True, null=True)),
                ('age_group', models.IntegerField(blank=True, null=True)),
                ('working_member', models.IntegerField(blank=True, null=True)),
                ('already_bought_property', models.IntegerField(blank=True, null=True)),
                ('nature_of_lead', models.IntegerField(blank=True, null=True)),
                ('number_of_visits', models.IntegerField(blank=True, null=True)),
                ('family_status', models.IntegerField(blank=True, null=True)),
                ('residential_status', models.IntegerField(blank=True, null=True)),
                ('residential_country', models.CharField(blank=True, max_length=300, null=True)),
                ('employment_status', models.IntegerField(blank=True, null=True)),
                ('profession', models.IntegerField(blank=True, null=True)),
                ('profession_other', models.CharField(blank=True, max_length=300, null=True)),
                ('nature_of_business', models.IntegerField(blank=True, null=True)),
                ('nob_other', models.CharField(blank=True, max_length=300, null=True)),
                ('lead_status', models.IntegerField(blank=True, null=True)),
                ('tracker', models.IntegerField(blank=True, null=True)),
                ('builder', models.IntegerField(blank=True, null=True)),
                ('lead_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='leads',
            name='accepted_status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='already_bought_property',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='assign_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='builder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='created_by_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='employment_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='family_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='leaddelete',
            field=models.CharField(blank=True, db_column='leadDelete', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='nature_of_business',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='nature_of_lead',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='nob_other',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='number_of_visits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='profession',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='profession_other',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='project_type_multiple',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='property_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='prospect_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='residential_country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='residential_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='response_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='source',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='tracker',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='working_member',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
